spring.datasource.url=jdbc:postgresql://localhost:5432/stock
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# This ensures Hibernate creates/updates tables automatically if they are missing
spring.jpa.hibernate.ddl-auto=update

# Useful for debugging when switching between databases
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect